### ISSUE TITLE
If there's an error with Valve's servers, reply with the database entry for that skin, if possible

### ISSUE THREAD

**Issue by Squamoto** [Step7750/CSGOFloat#46]
If Valve servers don't respond in time, and you have a database entry for that item ID, you could respond to the API query with that entry instead of sending out an error. If so, it should have an element indicating that it's a cached version and maybe the timestamp if you save those in the database.

**Comment by Step7750** [comment]
After looking at the code base briefly, it looks like this functionality is already implemented. https://github.com/Step7750/CSGOFloat/blob/4c25c66b86d27b2c546eca792b3e5009f91fecb3/index.js#L50

If we already have the item in the DB, a call to the GC is never made and we just return a reconstructed response from the database (this is fine since Valve's response is effectively immutable).  So there isn't an instance where Valve's servers don't respond in time and we'd have a cached copy to return afterwards since we would have never made that request to Valve in the first place if we already had the item in the db.
